### ISSUE TITLE
RuntimeError: expected scalar type Float but found Double

### ISSUE THREAD

**Issue by SamuelSchmidgall** [bamsumit/slayerPytorch#17]
I've been receiving the error "RuntimeError: expected scalar type Float but found Double" when running the test examples on a fresh install of slayerPytorch. After many attempts at fixing the issue, I've reinstalled Ubuntu 18.04 to a clean wipe yet am still getting the same error.

A list of things I've tried:
Installing Pytorch from source
Cuda version 9.2, 10.1, 10.2
Nvidia version 418, 440
Ubuntu 16.04, Ubuntu 18.04
Different gcc versions from 5-8
Changing 'nvcc': ['-arch=sm_60', '-O2', '-use_fast_math'] to 'nvcc': ['-arch=sm_50', '-O2', '-use_fast_math'] in the setup.py for both installs.
I have a GeForce GTX 960 GPU.

The output of the test examples:

Max PSP kernel: 195.0
Scaling neuron[scaleRho] by Max PSP Kernel @slayerLoihi
EEEEEE..E...EEE........
ERROR: test_slayer001 (unittest.loader._FailedTest)
ImportError: Failed to import test module: test_slayer001
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/sam/slayerPytorch-master/test/test_slayer001.py", line 31, in <module>
    a = slayer.psp(spike)
  File "/home/sam/slayerPytorch-master/test/../src/slayer.py", line 142, in psp
    return _pspFunction.apply(spike, self.srmKernel, self.simulation['Ts'])
  File "/home/sam/slayerPytorch-master/test/../src/slayer.py", line 672, in forward
    psp = slayerCuda.conv(spike.contiguous(), filter, Ts)
RuntimeError: expected scalar type Float but found Double

======================================================================
ERROR: test_slayer002 (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_slayer002
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/sam/slayerPytorch-master/test/test_slayer002.py", line 62, in <module>
    aIn      = slayer.psp(spikeIn)
  File "/home/sam/slayerPytorch-master/test/../src/slayer.py", line 142, in psp
    return _pspFunction.apply(spike, self.srmKernel, self.simulation['Ts'])
  File "/home/sam/slayerPytorch-master/test/../src/slayer.py", line 672, in forward
    psp = slayerCuda.conv(spike.contiguous(), filter, Ts)
RuntimeError: expected scalar type Float but found Double

======================================================================
ERROR: test_slayer003 (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_slayer003
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/sam/slayerPytorch-master/test/test_slayer003.py", line 67, in <module>
    spikeOut = snn.forward(spikeIn)
  File "/home/sam/slayerPytorch-master/test/test_slayer003.py", line 51, in forward
    spikeLayer1 = self.slayer.spike(self.slayer.psp(self.fc1(spikeInput)))
  File "/home/sam/slayerPytorch-master/test/../src/slayer.py", line 142, in psp
    return _pspFunction.apply(spike, self.srmKernel, self.simulation['Ts'])
  File "/home/sam/slayerPytorch-master/test/../src/slayer.py", line 672, in forward
    psp = slayerCuda.conv(spike.contiguous(), filter, Ts)
RuntimeError: expected scalar type Float but found Double

======================================================================
ERROR: test_slayer004 (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_slayer004
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/sam/slayerPytorch-master/test/test_slayer004.py", line 54, in <module>
    spikeOut = snn.forward(spikeIn)
  File "/home/sam/slayerPytorch-master/test/test_slayer004.py", line 40, in forward
    return self.slayer.spike(self.fc1(self.slayer.psp(spikeInput)))
  File "/home/sam/slayerPytorch-master/test/../src/slayer.py", line 142, in psp
    return _pspFunction.apply(spike, self.srmKernel, self.simulation['Ts'])
  File "/home/sam/slayerPytorch-master/test/../src/slayer.py", line 672, in forward
    psp = slayerCuda.conv(spike.contiguous(), filter, Ts)
RuntimeError: expected scalar type Float but found Double

======================================================================
ERROR: test_slayer005 (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_slayer005
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/sam/slayerPytorch-master/test/test_slayer005.py", line 82, in <module>
    spikeOut = snn.forward(spikeIn)
  File "/home/sam/slayerPytorch-master/test/test_slayer005.py", line 44, in forward
    spikeLayer1 = self.slayer.spike(self.fc1(self.slayer.psp(spikeInput)))
  File "/home/sam/slayerPytorch-master/test/../src/slayer.py", line 142, in psp
    return _pspFunction.apply(spike, self.srmKernel, self.simulation['Ts'])
  File "/home/sam/slayerPytorch-master/test/../src/slayer.py", line 672, in forward
    psp = slayerCuda.conv(spike.contiguous(), filter, Ts)
RuntimeError: expected scalar type Float but found Double

======================================================================
ERROR: test_slayer006 (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_slayer006
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/sam/slayerPytorch-master/test/test_slayer006.py", line 73, in <module>
    spikeOut = snn.forward(spikeIn)
  File "/home/sam/slayerPytorch-master/test/test_slayer006.py", line 42, in forward
    spikeLayer1 = self.slayer.spike(self.fc1(self.slayer.psp(spikeInput)))
  File "/home/sam/slayerPytorch-master/test/../src/slayer.py", line 142, in psp
    return _pspFunction.apply(spike, self.srmKernel, self.simulation['Ts'])
  File "/home/sam/slayerPytorch-master/test/../src/slayer.py", line 672, in forward
    psp = slayerCuda.conv(spike.contiguous(), filter, Ts)
RuntimeError: expected scalar type Float but found Double

======================================================================
ERROR: testOddDimension (test_slayer007.TestPooling)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sam/slayerPytorch-master/test/test_slayer007.py", line 78, in testOddDimension
    out = pool(inTensor)
  File "/home/sam/virtual_envs/spiking/lib/python3.6/site-packages/torch/nn/modules/module.py", line 562, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sam/virtual_envs/spiking/lib/python3.6/site-packages/slayerSNN-0.0.0-py3.6.egg/slayerSNN/slayer.py", line 522, in forward
    input = torch.cat((input, torch.zeros((input.shape[0], input.shape[1], input.shape[2], input.shape[3]%self.weight.shape[3], input.shape[4]), dtype=dtype).to(device)), 3)
RuntimeError: CUDA out of memory. Tried to allocate 636.00 MiB (GPU 0; 3.95 GiB total capacity; 3.07 GiB already allocated; 120.00 MiB free; 3.10 GiB reserved in total by PyTorch)

======================================================================
ERROR: test_slayer010 (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_slayer010
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/sam/slayerPytorch-master/test/test_slayer010.py", line 61, in <module>
    psp = slayer.psp(spikeIn)
  File "/home/sam/virtual_envs/spiking/lib/python3.6/site-packages/slayerSNN-0.0.0-py3.6.egg/slayerSNN/slayer.py", line 142, in psp
    return _pspFunction.apply(spike, self.srmKernel, self.simulation['Ts'])
  File "/home/sam/virtual_envs/spiking/lib/python3.6/site-packages/slayerSNN-0.0.0-py3.6.egg/slayerSNN/slayer.py", line 672, in forward
    psp = slayerCuda.conv(spike.contiguous(), filter, Ts)
RuntimeError: expected scalar type Float but found Double

======================================================================
ERROR: test_slayer011 (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_slayer011
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/sam/slayerPytorch-master/test/test_slayer011.py", line 35, in <module>
    pspGT = slayer.psp(spikeIn)
  File "/home/sam/virtual_envs/spiking/lib/python3.6/site-packages/slayerSNN-0.0.0-py3.6.egg/slayerSNN/slayer.py", line 142, in psp
    return _pspFunction.apply(spike, self.srmKernel, self.simulation['Ts'])
  File "/home/sam/virtual_envs/spiking/lib/python3.6/site-packages/slayerSNN-0.0.0-py3.6.egg/slayerSNN/slayer.py", line 672, in forward
    psp = slayerCuda.conv(spike.contiguous(), filter, Ts)
RuntimeError: expected scalar type Float but found Double

======================================================================
ERROR: test_slayer012 (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_slayer012
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/sam/slayerPytorch-master/test/test_slayer012.py", line 41, in <module>
    pspGT = slayer.psp(spikeIn)
  File "/home/sam/virtual_envs/spiking/lib/python3.6/site-packages/slayerSNN-0.0.0-py3.6.egg/slayerSNN/slayer.py", line 142, in psp
    return _pspFunction.apply(spike, self.srmKernel, self.simulation['Ts'])
  File "/home/sam/virtual_envs/spiking/lib/python3.6/site-packages/slayerSNN-0.0.0-py3.6.egg/slayerSNN/slayer.py", line 672, in forward
    psp = slayerCuda.conv(spike.contiguous(), filter, Ts)
RuntimeError: expected scalar type Float but found Double

----------------------------------------------------------------------
Ran 23 tests in 7.518s

FAILED (errors=10)

Any ideas on what might be going on?

Thanks for the help,
Sam

**Comment by bamsumit** [comment]
Hi, It looks like your torch default data type is not `torch.float32`.
Try `torch.get_default_dtype()`
It is most likely `torch.float64` instead of `torch.float32`.
If that's the case, you may try `torch.set_default_dtype(torch.float32)`. I am not sure if you need to do this once or for every script.

**Comment by Termynator** [comment]
wow I have been struggling with this as well excellent timing Sam. I have tried your fix of checking the default torch type.
The default type is `torch.float32`
I changed to `torch.float64` to no avail.
I also checked the dtype of the tensors being passed to 
`return _pspFunction.apply(spike, self.srmKernel, self.simulation['Ts'])`
and `spike` is indeed a `torch.float`
it looks like the `spike.contiguous()` could be the issue.
I am using cuda 10.2 and python 3.8.2.

**Comment by bamsumit** [comment]
Can one of you help me run the following sequence of code and tell me what happens:
```
import torch
import slayerSNN
import slayerCuda
inp = torch.rand((16, 100)).to('cuda')
filter = torch.rand((16)).to('cuda')
out = slayerCuda.conv(inp, filter, 1)
print(inp.dtype, filter.dtype, out.dtype)
out = slayerCuda.conv(inp, filter, 1)
print(inp.contiguous().dtype)
out = slayerCuda.conv(inp.contiguous(), filter, 1)
```

**Comment by Termynator** [comment]
here is the output.
'torch.float32 torch.float32 torch.float32'
'torch.float32'
i also printed the last out's dtype
'torch.float32'

**Comment by bamsumit** [comment]
Since you already checked the `dtype` of spike and found it to be `torch.float32`, I suspect filter is not of type `torch.float32`. Try this out:
In `src/slayer.py`, go to line 101 and 112 and change `torch.tensor` to `torch.FloatTensor`. Let me know if that resolves your issue.

**Comment by Termynator** [comment]
That seems to have done it!
You are the man!

**Comment by bamsumit** [comment]
That's great. 
However, a long-term fix would be to set your default tensor to FloatTensor as there are many other places where this behavior is used. PyTorch documentation says: `torch.Tensor` is an alias for the default tensor type (`torch.FloatTensor`). So your default tensor type in the system is something else.
Can you try `torch.set_default_tensor_type(torch.FloatTensor)`. This would be a long-term fix.

**Comment by Termynator** [comment]
I will keep that in mind.
All the tests ran without issue and I am currently running nmnistCNN.py.
Thanks again

**Comment by bamsumit** [comment]
Great

**Comment by SamuelSchmidgall** [comment]
Thank you for the quick feedback. I was able to solve the issue by changing

`torch.tensor(srmKernel)` and `torch.tensor(refKernel)` 
->
`torch.tensor(srmKernel).float()` and `torch.tensor(refKernel).float()` 

in the slayer.py class.
