### ISSUE TITLE
CUDA 11 / RTX 3090 compatibility?

### ISSUE THREAD

**Issue by zenmar** [bamsumit/slayerPytorch#78]
Hi,

I'm looking to install and use SLAYER on a new machine, which has RTX3090 GPUs.

Sadly, they require another PyTorch installation.
("GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation")

As in [here](https://discuss.pytorch.org/t/rtx-3090-compatibility/110014) I reinstalled PyTorch with the CUDA11 runtime, which worked fine.

But now, SLAYER seems to break, and I'm getting the following error when trying to import it:

`ImportError: /home/xxx/envs/yyy/lib/python3.8/site-packages/slayerCuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor8data_ptrIfEEPT_v
`

Is there a workaround to make SLAYER work in this setup? 

Thanks in advance

**Comment by bamsumit** [comment]
I have the following combination working for RTX 3090
* torch: 1.7.1+cu110
* torchvision: 0.8.2+cu110
* nvidia driver: cuda 11.2
* nvcc compiler version: cuda 11.1

Typically you would want all the cuda versions same, but since the GPU is new, the versions are all over the place for now.

**Comment by zenmar** [comment]
Thanks, this worked!
