### ISSUE TITLE
Error when running unittest - Tests failing and system doesn't seem to train

### ISSUE THREAD

**Issue by strathpaulkirkland** [bamsumit/slayerPytorch#9]
Hi, i can't seem to get Slayer to install correctly, originally had issues with Cuda 10 but i've since swapped machines and now have it up and running to this point on my laptop. it just seems unable to train as the loss doesn't seem to improve as i tested this on the sample and the accuracy just remains very low?

Any suggestions as to what I have done wrong?
```

Max PSP kernel: 195.0
Scaling neuron[scaleRho] by Max PSP Kernel @slayerLoihi
..F.FF....E.FF..F..FFFFF....
======================================================================
ERROR: testOddDimension (test_slayer007.TestPooling)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/slayerPytorch/test/test_slayer007.py", line 77, in testOddDimension
    inTensor = torch.randn((4, 8, 101, 101, 500)).to(device)
RuntimeError: CUDA out of memory. Tried to allocate 624.00 MiB (GPU 0; 3.95 GiB total capacity; 2.01 GiB already allocated; 464.19 MiB free; 179.17 MiB cached)

======================================================================
FAIL: testOut (test_slayer002.testSpike)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/slayerPytorch/test/test_slayer002.py", line 196, in testOut
    self.assertEqual(torch.norm(spikeGT - spikeOut), 0, 'Error mus be zero.')
AssertionError: tensor(174.0688, device='cuda:0', grad_fn=<NormBackward0>) != 0 : Error mus be zero.

======================================================================
FAIL: test (test_slayer003.testGradients)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/slayerPytorch/test/test_slayer003.py", line 100, in test
    self.assertTrue(errorLayer2 < 1e-4, 'Error must be close to zero.')
AssertionError: False is not true : Error must be close to zero.

======================================================================
FAIL: test (test_slayer004.testSpikeClassifier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/slayerPytorch/test/test_slayer004.py", line 72, in test
    self.assertEqual(predict.getClass(spikeOut), 21, 'Correct class is 21.')
AssertionError: tensor([1]) != 21 : Correct class is 21.

======================================================================
FAIL: testShift (test_slayer009.TestDelay)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/slayerPytorch/test/test_slayer009.py", line 81, in testShift
    self.assertEqual(netError, 0, 'Shift error must be zero.')
AssertionError: 14703127.613067627 != 0 : Shift error must be zero.

======================================================================
FAIL: testShiftPerNeuron (test_slayer009.TestDelay)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/slayerPytorch/test/test_slayer009.py", line 63, in testShiftPerNeuron
    self.assertEqual(netError, 0, 'Shift (per neuron) error must be zero.')
AssertionError: 14695754.566619873 != 0 : Shift (per neuron) error must be zero.

======================================================================
FAIL: test (test_slayer011.TestPspLayer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/slayerPytorch/test/test_slayer011.py", line 43, in test
    self.assertTrue(error < 1e-6, 'Result from Psp function and Psp layer must match.')
AssertionError: tensor(0, device='cuda:0', dtype=torch.uint8) is not true : Result from Psp function and Psp layer must match.

======================================================================
FAIL: testValues (test_slayer012.TestPspFilter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/slayerPytorch/test/test_slayer012.py", line 53, in testValues
    self.assertTrue(error < 1e-6, 'Result from Psp function and Psp filter bank must match.')
AssertionError: tensor(0, device='cuda:0', dtype=torch.uint8) is not true : Result from Psp function and Psp filter bank must match.

======================================================================
FAIL: testHidden (test_slayerLoihi001.testLoihiSpikes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/slayerPytorch/test/test_slayerLoihi001.py", line 107, in testHidden
    self.assertTrue(error<1e-3, 'Hidden spike and ground truth must match.')
AssertionError: False is not true : Hidden spike and ground truth must match.

======================================================================
FAIL: testOutput (test_slayerLoihi001.testLoihiSpikes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/slayerPytorch/test/test_slayerLoihi001.py", line 121, in testOutput
    self.assertTrue(error<1e-3, 'Output spike and ground truth must match.')
AssertionError: False is not true : Output spike and ground truth must match.

======================================================================
FAIL: testHidden (test_slayerLoihi001.testLoihiVoltage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/slayerPytorch/test/test_slayerLoihi001.py", line 127, in testHidden
    self.assertTrue(error<1e-3, 'Hidden voltage and ground truth must match.')
AssertionError: False is not true : Hidden voltage and ground truth must match.

======================================================================
FAIL: testOutput (test_slayerLoihi001.testLoihiVoltage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/slayerPytorch/test/test_slayerLoihi001.py", line 131, in testOutput
    self.assertTrue(error<1e-3, 'Hidden voltage and ground truth must match.')
AssertionError: False is not true : Hidden voltage and ground truth must match.

----------------------------------------------------------------------
Ran 28 tests in 8.335s

FAILED (failures=11, errors=1)
`
```

**Comment by bamsumit** [comment]
You seem to be failing the unittests. Can you tell me the model and compute capability of your GPU? Currently, the code compiles for cc>=6.0 . I suspect that might be the reason.

**Comment by bamsumit** [comment]
Is your problem solved?
